# Site settings
title: 418 & delphi
email: 418.and.delphi@gmail.com
url: https://418-and-delphi.github.io
description: "Welcome. This is Satoru's little Tea Salon, 418 and Delphi. I'm working on a variety of personal projects. I hope you find a little solace, happiness, and a future here."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#fdf5ce'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Instagram
    url: https://instagram.com/418.and.delphi
  - title: Blog
    url: https://www.notion.so/418-n-delphi/Satoru-s-Tea-Salon-81b342969e204655ae88d47f53f95066?pvs=4
  - title: github
    url: https://github.com/418-and-delphi

# Build settings
markdown: kramdown
permalink: pretty
